tmdb.api.key=eacc3f392cd0c8a34c3158c73f59a233
tmdb.api.base-url=https://api.themoviedb.org/3
tmdb.api.image-base-url=https://image.tmdb.org/t/p/w500


spring.application.name=moviecatalogue
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

